##### Copyright 2020 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Working with preprocessing layers

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/guide/keras/preprocessing_layers"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/snapshot-keras/site/en/guide/keras/preprocessing_layers.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/keras-team/keras-io/blob/master/guides/preprocessing_layers.py"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/guide/keras/preprocessing_layers.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

## Keras preprocessing

The Keras preprocessing layers API allows developers to build Keras-native input
processing pipelines. These input processing pipelines can be used as independent
preprocessing code in non-Keras workflows, combined directly with Keras models, and
exported as part of a Keras SavedModel.

With Keras preprocessing layers, you can build and export models that are truly
end-to-end: models that accept raw images or raw structured data as input; models that
handle feature normalization or feature value indexing on their own.

## Available preprocessing

### Text preprocessing

- `tf.keras.layers.TextVectorization`: turns raw strings into an encoded
  representation that can be read by an `Embedding` layer or `Dense` layer.

### Numerical features preprocessing

- `tf.keras.layers.Normalization`: performs feature-wise normalize of
  input features.
- `tf.keras.layers.Discretization`: turns continuous numerical features
  into integer categorical features.

### Categorical features preprocessing

- `tf.keras.layers.CategoryEncoding`: turns integer categorical features
  into one-hot, multi-hot, or count dense representations.
- `tf.keras.layers.Hashing`: performs categorical feature hashing, also known as
  the "hashing trick".
- `tf.keras.layers.StringLookup`: turns string categorical values an encoded
  representation that can be read by an `Embedding` layer or `Dense` layer.
- `tf.keras.layers.IntegerLookup`: turns integer categorical values into an
  encoded representation that can be read by an `Embedding` layer or `Dense`
  layer.


### Image preprocessing

These layers are for standardizing the inputs of an image model.

- `tf.keras.layers.Resizing`: resizes a batch of images to a target size.
- `tf.keras.layers.Rescaling`: rescales and offsets the values of a batch of
  image (e.g. go from inputs in the `[0, 255]` range to inputs in the `[0, 1]`
  range.
- `tf.keras.layers.CenterCrop`: returns a center crop of a batch of images.

### Image data augmentation

These layers apply random augmentation transforms to a batch of images. They
are only active during training.

- `tf.keras.layers.RandomCrop`
- `tf.keras.layers.RandomFlip`
- `tf.keras.layers.RandomTranslation`
- `tf.keras.layers.RandomRotation`
- `tf.keras.layers.RandomZoom`
- `tf.keras.layers.RandomHeight`
- `tf.keras.layers.RandomWidth`
- `tf.keras.layers.RandomContrast`

## The `adapt()` method

Some preprocessing layers have an internal state that can be computed based on
a sample of the training data. The list of stateful preprocessing layers is:

- `TextVectorization`: holds a mapping between string tokens and integer indices
- `StringLookup` and `IntegerLookup`: hold a mapping between input values and integer
indices.
- `Normalization`: holds the mean and standard deviation of the features.
- `Discretization`: holds information about value bucket boundaries.

Crucially, these layers are **non-trainable**. Their state is not set during training; it
must be set **before training**, either by initializing them from a precomputed constant,
or by "adapting" them on data.

You set the state of a preprocessing layer by exposing it to training data, via the
`adapt()` method:

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

data = np.array([[0.1, 0.2, 0.3], [0.8, 0.9, 1.0], [1.5, 1.6, 1.7],])
layer = layers.Normalization()
layer.adapt(data)
normalized_data = layer(data)

print("Features mean: %.2f" % (normalized_data.numpy().mean()))
print("Features std: %.2f" % (normalized_data.numpy().std()))

Features mean: -0.00
Features std: 1.00


The `adapt()` method takes either a Numpy array or a `tf.data.Dataset` object. In the
case of `StringLookup` and `TextVectorization`, you can also pass a list of strings:

In [3]:
data = [
    "ξεῖν᾽, ἦ τοι μὲν ὄνειροι ἀμήχανοι ἀκριτόμυθοι",
    "γίγνοντ᾽, οὐδέ τι πάντα τελείεται ἀνθρώποισι.",
    "δοιαὶ γάρ τε πύλαι ἀμενηνῶν εἰσὶν ὀνείρων:",
    "αἱ μὲν γὰρ κεράεσσι τετεύχαται, αἱ δ᾽ ἐλέφαντι:",
    "τῶν οἳ μέν κ᾽ ἔλθωσι διὰ πριστοῦ ἐλέφαντος,",
    "οἵ ῥ᾽ ἐλεφαίρονται, ἔπε᾽ ἀκράαντα φέροντες:",
    "οἱ δὲ διὰ ξεστῶν κεράων ἔλθωσι θύραζε,",
    "οἵ ῥ᾽ ἔτυμα κραίνουσι, βροτῶν ὅτε κέν τις ἴδηται.",
]
layer = layers.TextVectorization()
layer.adapt(data)
vectorized_text = layer(data)
print(vectorized_text)

tf.Tensor(
[[37 12 25  5  9 20 21  0  0]
 [51 34 27 33 29 18  0  0  0]
 [49 52 30 31 19 46 10  0  0]
 [ 7  5 50 43 28  7 47 17  0]
 [24 35 39 40  3  6 32 16  0]
 [ 4  2 15 14 22 23  0  0  0]
 [36 48  6 38 42  3 45  0  0]
 [ 4  2 13 41 53  8 44 26 11]], shape=(8, 9), dtype=int64)


In addition, adaptable layers always expose an option to directly set state via
constructor arguments or weight assignment. If the intended state values are known at
layer construction time, or are calculated outside of the `adapt()` call, they can be set
without relying on the layer's internal computation. For instance, if external vocabulary
files for the `TextVectorization`, `StringLookup`, or `IntegerLookup` layers already
exist, those can be loaded directly into the lookup tables by passing a path to the
vocabulary file in the layer's constructor arguments.

Here's an example where we instantiate a `StringLookup` layer with precomputed vocabulary:

In [4]:
vocab = ["a", "b", "c", "d"]
data = tf.constant([["a", "c", "d"], ["d", "z", "b"]])
layer = layers.StringLookup(vocabulary=vocab)
vectorized_data = layer(data)
print(vectorized_data)

tf.Tensor(
[[1 3 4]
 [4 0 2]], shape=(2, 3), dtype=int64)


## Preprocessing data before the model or inside the model

There are two ways you could be using preprocessing layers:

**Option 1:** Make them part of the model, like this:

```python
inputs = keras.Input(shape=input_shape)
x = preprocessing_layer(inputs)
outputs = rest_of_the_model(x)
model = keras.Model(inputs, outputs)
```

With this option, preprocessing will happen on device, synchronously with the rest of the
model execution, meaning that it will benefit from GPU acceleration.
If you're training on GPU, this is the best option for the `Normalization` layer, and for
all image preprocessing and data augmentation layers.

**Option 2:** apply it to your `tf.data.Dataset`, so as to obtain a dataset that yields
batches of preprocessed data, like this:

```python
dataset = dataset.map(lambda x, y: (preprocessing_layer(x), y))
```

With this option, your preprocessing will happen on CPU, asynchronously, and will be
buffered before going into the model.
In addition, if you call `dataset.prefetch(tf.data.AUTOTUNE)` on your dataset,
the preprocessing will happen efficiently in parallel with training:

```python
dataset = dataset.map(lambda x, y: (preprocessing_layer(x), y))
dataset = dataset.prefetch(tf.data.AUTOTUNE)
model.fit(dataset, ...)
```

This is the best option for `TextVectorization`, and all structured data preprocessing
layers. It can also be a good option if you're training on CPU
and you use image preprocessing layers.

**When running on TPU, you should always place preprocessing layers in the `tf.data` pipeline**
(with the exception of `Normalization` and `Rescaling`, which run fine on TPU and are commonly
used as the first layer is an image model).

## Benefits of doing preprocessing inside the model at inference time

Even if you go with option 2, you may later want to export an inference-only end-to-end
model that will include the preprocessing layers. The key benefit to doing this is that
**it makes your model portable** and it **helps reduce the
[training/serving skew](https://developers.google.com/machine-learning/guides/rules-of-ml#training-serving_skew)**.

When all data preprocessing is part of the model, other people can load and use your
model without having to be aware of how each feature is expected to be encoded &
normalized. Your inference model will be able to process raw images or raw structured
data, and will not require users of the model to be aware of the details of e.g. the
tokenization scheme used for text, the indexing scheme used for categorical features,
whether image pixel values are normalized to `[-1, +1]` or to `[0, 1]`, etc. This is
especially powerful if you're exporting
your model to another runtime, such as TensorFlow.js: you won't have to
reimplement your preprocessing pipeline in JavaScript.

If you initially put your preprocessing layers in your `tf.data` pipeline,
you can export an inference model that packages the preprocessing.
Simply instantiate a new model that chains
your preprocessing layers and your training model:

```python
inputs = keras.Input(shape=input_shape)
x = preprocessing_layer(inputs)
outputs = training_model(x)
inference_model = keras.Model(inputs, outputs)
```

## Quick recipes

### Image data augmentation

Note that image data augmentation layers are only active during training (similarly to
the `Dropout` layer).

In [5]:
from tensorflow import keras
from tensorflow.keras import layers

# Create a data augmentation stage with horizontal flipping, rotations, zooms
data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.1),
        layers.RandomZoom(0.1),
    ]
)

# Load some data
(x_train, y_train), _ = keras.datasets.cifar10.load_data()
input_shape = x_train.shape[1:]
classes = 10

# Create a tf.data pipeline of augmented images (and their labels)
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.batch(16).map(lambda x, y: (data_augmentation(x), y))


# Create a model and train it on the augmented image data
inputs = keras.Input(shape=input_shape)
x = layers.Rescaling(1.0 / 255)(inputs)  # Rescale inputs
outputs = keras.applications.ResNet50(  # Add the rest of the model
    weights=None, input_shape=input_shape, classes=classes
)(x)
model = keras.Model(inputs, outputs)
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy")
model.fit(train_dataset, steps_per_epoch=5)

    16384/170498071 [..............................] - ETA: 0s

    40960/170498071 [..............................] - ETA: 6:35

    90112/170498071 [..............................] - ETA: 5:52

   204800/170498071 [..............................] - ETA: 3:52

   434176/170498071 [..............................] - ETA: 2:26

   876544/170498071 [..............................] - ETA: 1:30

  1761280/170498071 [..............................] - ETA: 50s 

  2154496/170498071 [..............................] - ETA: 45s

  3563520/170498071 [..............................] - ETA: 30s

  5283840/170498071 [..............................] - ETA: 22s

  6823936/170498071 [>.............................] - ETA: 18s

  8118272/170498071 [>.............................] - ETA: 16s

  9609216/170498071 [>.............................] - ETA: 14s

 11083776/170498071 [>.............................] - ETA: 13s

 12550144/170498071 [=>............................] - ETA: 12s

 13983744/170498071 [=>............................] - ETA: 11s

 15425536/170498071 [=>............................] - ETA: 10s

 16867328/170498071 [=>............................] - ETA: 10s

 18276352/170498071 [==>...........................] - ETA: 9s 

 19783680/170498071 [==>...........................] - ETA: 9s

 21176320/170498071 [==>...........................] - ETA: 8s

 22732800/170498071 [==>...........................] - ETA: 8s

 24092672/170498071 [===>..........................] - ETA: 8s

 25550848/170498071 [===>..........................] - ETA: 8s

 27025408/170498071 [===>..........................] - ETA: 7s

 28467200/170498071 [====>.........................] - ETA: 7s

 29958144/170498071 [====>.........................] - ETA: 7s

 31383552/170498071 [====>.........................] - ETA: 7s

 32743424/170498071 [====>.........................] - ETA: 7s

 34217984/170498071 [=====>........................] - ETA: 6s

 35594240/170498071 [=====>........................] - ETA: 6s

 37003264/170498071 [=====>........................] - ETA: 6s

 38461440/170498071 [=====>........................] - ETA: 6s

 39886848/170498071 [======>.......................] - ETA: 6s

 41230336/170498071 [======>.......................] - ETA: 6s

 42704896/170498071 [======>.......................] - ETA: 6s

 44146688/170498071 [======>.......................] - ETA: 5s

 45522944/170498071 [=======>......................] - ETA: 5s

 46997504/170498071 [=======>......................] - ETA: 5s

 48422912/170498071 [=======>......................] - ETA: 5s

 49815552/170498071 [=======>......................] - ETA: 5s

 51257344/170498071 [========>.....................] - ETA: 5s

 52666368/170498071 [========>.....................] - ETA: 5s

 54042624/170498071 [========>.....................] - ETA: 5s

 55468032/170498071 [========>.....................] - ETA: 5s

 56860672/170498071 [=========>....................] - ETA: 5s

 58236928/170498071 [=========>....................] - ETA: 4s

 59596800/170498071 [=========>....................] - ETA: 4s

 61071360/170498071 [=========>....................] - ETA: 4s

 62545920/170498071 [==========>...................] - ETA: 4s

 63954944/170498071 [==========>...................] - ETA: 4s

 65363968/170498071 [==========>...................] - ETA: 4s

 66822144/170498071 [==========>...................] - ETA: 4s

 68247552/170498071 [===========>..................] - ETA: 4s

 69591040/170498071 [===========>..................] - ETA: 4s

 71016448/170498071 [===========>..................] - ETA: 4s

 72392704/170498071 [===========>..................] - ETA: 4s

 73687040/170498071 [===========>..................] - ETA: 4s

 75079680/170498071 [============>.................] - ETA: 4s

 76472320/170498071 [============>.................] - ETA: 3s

 77815808/170498071 [============>.................] - ETA: 3s

 79110144/170498071 [============>.................] - ETA: 3s

 80551936/170498071 [=============>................] - ETA: 3s

 81879040/170498071 [=============>................] - ETA: 3s

 83566592/170498071 [=============>................] - ETA: 3s

 85106688/170498071 [=============>................] - ETA: 3s

 86769664/170498071 [==============>...............] - ETA: 3s

 88039424/170498071 [==============>...............] - ETA: 3s

 89759744/170498071 [==============>...............] - ETA: 3s

 91004928/170498071 [===============>..............] - ETA: 3s

 92676096/170498071 [===============>..............] - ETA: 3s

 94068736/170498071 [===============>..............] - ETA: 3s

 95756288/170498071 [===============>..............] - ETA: 3s

 97083392/170498071 [================>.............] - ETA: 3s

 98787328/170498071 [================>.............] - ETA: 2s

100147200/170498071 [================>.............] - ETA: 2s

101801984/170498071 [================>.............] - ETA: 2s

103194624/170498071 [=================>............] - ETA: 2s

104898560/170498071 [=================>............] - ETA: 2s

106258432/170498071 [=================>............] - ETA: 2s

107945984/170498071 [=================>............] - ETA: 2s

109256704/170498071 [==================>...........] - ETA: 2s

110911488/170498071 [==================>...........] - ETA: 2s

112271360/170498071 [==================>...........] - ETA: 2s

113860608/170498071 [===================>..........] - ETA: 2s

115269632/170498071 [===================>..........] - ETA: 2s

116826112/170498071 [===================>..........] - ETA: 2s

118284288/170498071 [===================>..........] - ETA: 2s

119906304/170498071 [====================>.........] - ETA: 1s

121298944/170498071 [====================>.........] - ETA: 1s

122953728/170498071 [====================>.........] - ETA: 1s

124313600/170498071 [====================>.........] - ETA: 1s

125984768/170498071 [=====================>........] - ETA: 1s

127311872/170498071 [=====================>........] - ETA: 1s

128983040/170498071 [=====================>........] - ETA: 1s

130359296/170498071 [=====================>........] - ETA: 1s

132030464/170498071 [======================>.......] - ETA: 1s

133423104/170498071 [======================>.......] - ETA: 1s

135094272/170498071 [======================>.......] - ETA: 1s

136486912/170498071 [=======================>......] - ETA: 1s

138158080/170498071 [=======================>......] - ETA: 1s

139485184/170498071 [=======================>......] - ETA: 1s

141312000/170498071 [=======================>......] - ETA: 1s

142721024/170498071 [========================>.....] - ETA: 1s

144744448/170498071 [========================>.....] - ETA: 0s

145858560/170498071 [========================>.....] - ETA: 0s

148250624/170498071 [=========================>....] - ETA: 0s

149413888/170498071 [=========================>....] - ETA: 0s

151691264/170498071 [=========================>....] - ETA: 0s

152952832/170498071 [=========================>....] - ETA: 0s

154984448/170498071 [==========================>...] - ETA: 0s

156508160/170498071 [==========================>...] - ETA: 0s

158146560/170498071 [==========================>...] - ETA: 0s

160071680/170498071 [===========================>..] - ETA: 0s

161603584/170498071 [===========================>..] - ETA: 0s

163635200/170498071 [===========================>..] - ETA: 0s

165109760/170498071 [============================>.] - ETA: 0s

166764544/170498071 [============================>.] - ETA: 0s

168402944/170498071 [============================>.] - ETA: 0s

170500096/170498071 [==============================] - 6s 0us/step


170508288/170498071 [==============================] - 6s 0us/step


1/5 [=====>........................] - ETA: 44s - loss: 4.6052

3/5 [=================>............] - ETA: 0s - loss: 7.4746 

5/5 [==============================] - ETA: 0s - loss: 8.8927

5/5 [==============================] - 11s 44ms/step - loss: 8.8927


You can see a similar setup in action in the example
[image classification from scratch](https://keras.io/examples/vision/image_classification_from_scratch/).

### Normalizing numerical features

In [6]:
# Load some data
(x_train, y_train), _ = keras.datasets.cifar10.load_data()
x_train = x_train.reshape((len(x_train), -1))
input_shape = x_train.shape[1:]
classes = 10

# Create a Normalization layer and set its internal state using the training data
normalizer = layers.Normalization()
normalizer.adapt(x_train)

# Create a model that include the normalization layer
inputs = keras.Input(shape=input_shape)
x = normalizer(inputs)
outputs = layers.Dense(classes, activation="softmax")(x)
model = keras.Model(inputs, outputs)

# Train the model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
model.fit(x_train, y_train)

   1/1563 [..............................] - ETA: 5:09 - loss: 3.0215

  30/1563 [..............................] - ETA: 2s - loss: 2.5136  

  60/1563 [>.............................] - ETA: 2s - loss: 2.3844

  89/1563 [>.............................] - ETA: 2s - loss: 2.3312

 118/1563 [=>............................] - ETA: 2s - loss: 2.3270

 147/1563 [=>............................] - ETA: 2s - loss: 2.2865

 176/1563 [==>...........................] - ETA: 2s - loss: 2.2656

 206/1563 [==>...........................] - ETA: 2s - loss: 2.2349

 235/1563 [===>..........................] - ETA: 2s - loss: 2.2238

 264/1563 [====>.........................] - ETA: 2s - loss: 2.2145

 293/1563 [====>.........................] - ETA: 2s - loss: 2.2032

 322/1563 [=====>........................] - ETA: 2s - loss: 2.1974

 350/1563 [=====>........................] - ETA: 2s - loss: 2.1971

 377/1563 [======>.......................] - ETA: 2s - loss: 2.1874

 404/1563 [======>.......................] - ETA: 2s - loss: 2.1835

 432/1563 [=======>......................] - ETA: 1s - loss: 2.1821

 460/1563 [=======>......................] - ETA: 1s - loss: 2.1835

 488/1563 [========>.....................] - ETA: 1s - loss: 2.1794

 516/1563 [========>.....................] - ETA: 1s - loss: 2.1748

 544/1563 [=========>....................] - ETA: 1s - loss: 2.1772

 573/1563 [=========>....................] - ETA: 1s - loss: 2.1770

 602/1563 [==========>...................] - ETA: 1s - loss: 2.1699

 630/1563 [===========>..................] - ETA: 1s - loss: 2.1727

 658/1563 [===========>..................] - ETA: 1s - loss: 2.1734

 685/1563 [============>.................] - ETA: 1s - loss: 2.1739

 712/1563 [============>.................] - ETA: 1s - loss: 2.1716

 740/1563 [=============>................] - ETA: 1s - loss: 2.1688

 768/1563 [=============>................] - ETA: 1s - loss: 2.1658

 796/1563 [==============>...............] - ETA: 1s - loss: 2.1682

 824/1563 [==============>...............] - ETA: 1s - loss: 2.1655

 851/1563 [===============>..............] - ETA: 1s - loss: 2.1637

 878/1563 [===============>..............] - ETA: 1s - loss: 2.1641

 904/1563 [================>.............] - ETA: 1s - loss: 2.1624

 930/1563 [================>.............] - ETA: 1s - loss: 2.1600

 956/1563 [=================>............] - ETA: 1s - loss: 2.1577

 981/1563 [=================>............] - ETA: 1s - loss: 2.1567

1008/1563 [==================>...........] - ETA: 1s - loss: 2.1542

1036/1563 [==================>...........] - ETA: 0s - loss: 2.1548

1064/1563 [===================>..........] - ETA: 0s - loss: 2.1513

1091/1563 [===================>..........] - ETA: 0s - loss: 2.1492

1119/1563 [====================>.........] - ETA: 0s - loss: 2.1485

1146/1563 [====================>.........] - ETA: 0s - loss: 2.1460

1174/1563 [=====================>........] - ETA: 0s - loss: 2.1442

1203/1563 [======================>.......] - ETA: 0s - loss: 2.1418

1231/1563 [======================>.......] - ETA: 0s - loss: 2.1399

1259/1563 [=======================>......] - ETA: 0s - loss: 2.1374

1286/1563 [=======================>......] - ETA: 0s - loss: 2.1353

1314/1563 [========================>.....] - ETA: 0s - loss: 2.1348

1342/1563 [========================>.....] - ETA: 0s - loss: 2.1340

1369/1563 [=========================>....] - ETA: 0s - loss: 2.1342

1397/1563 [=========================>....] - ETA: 0s - loss: 2.1343

1425/1563 [==========================>...] - ETA: 0s - loss: 2.1332

1453/1563 [==========================>...] - ETA: 0s - loss: 2.1332

1481/1563 [===========================>..] - ETA: 0s - loss: 2.1327

1508/1563 [===========================>..] - ETA: 0s - loss: 2.1313

1535/1563 [============================>.] - ETA: 0s - loss: 2.1306

1563/1563 [==============================] - ETA: 0s - loss: 2.1304

1563/1563 [==============================] - 3s 2ms/step - loss: 2.1304


### Encoding string categorical features via one-hot encoding

In [7]:
# Define some toy data
data = tf.constant([["a"], ["b"], ["c"], ["b"], ["c"], ["a"]])

# Use StringLookup to build an index of the feature values and encode output.
lookup = layers.StringLookup(output_mode="one_hot")
lookup.adapt(data)

# Convert new test data (which includes unknown feature values)
test_data = tf.constant([["a"], ["b"], ["c"], ["d"], ["e"], [""]])
encoded_data = lookup(test_data)
print(encoded_data)

tf.Tensor(
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]], shape=(6, 4), dtype=float32)


Note that, here, index 0 is reserved for out-of-vocabulary values
(values that were not seen during `adapt()`).

You can see the `StringLookup` in action in the
[Structured data classification from scratch](https://keras.io/examples/structured_data/structured_data_classification_from_scratch/)
example.

### Encoding integer categorical features via one-hot encoding

In [8]:
# Define some toy data
data = tf.constant([[10], [20], [20], [10], [30], [0]])

# Use IntegerLookup to build an index of the feature values and encode output.
lookup = layers.IntegerLookup(output_mode="one_hot")
lookup.adapt(data)

# Convert new test data (which includes unknown feature values)
test_data = tf.constant([[10], [10], [20], [50], [60], [0]])
encoded_data = lookup(test_data)
print(encoded_data)

tf.Tensor(
[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]], shape=(6, 5), dtype=float32)


Note that index 0 is reserved for missing values (which you should specify as the value
0), and index 1 is reserved for out-of-vocabulary values (values that were not seen
during `adapt()`). You can configure this by using the `mask_token` and `oov_token`
constructor arguments  of `IntegerLookup`.

You can see the `IntegerLookup` in action in the example
[structured data classification from scratch](https://keras.io/examples/structured_data/structured_data_classification_from_scratch/).

### Applying the hashing trick to an integer categorical feature

If you have a categorical feature that can take many different values (on the order of
10e3 or higher), where each value only appears a few times in the data,
it becomes impractical and ineffective to index and one-hot encode the feature values.
Instead, it can be a good idea to apply the "hashing trick": hash the values to a vector
of fixed size. This keeps the size of the feature space manageable, and removes the need
for explicit indexing.

In [9]:
# Sample data: 10,000 random integers with values between 0 and 100,000
data = np.random.randint(0, 100000, size=(10000, 1))

# Use the Hashing layer to hash the values to the range [0, 64]
hasher = layers.Hashing(num_bins=64, salt=1337)

# Use the CategoryEncoding layer to multi-hot encode the hashed values
encoder = layers.CategoryEncoding(num_tokens=64, output_mode="multi_hot")
encoded_data = encoder(hasher(data))
print(encoded_data.shape)

(10000, 64)


### Encoding text as a sequence of token indices

This is how you should preprocess text to be passed to an `Embedding` layer.

In [10]:
# Define some text data to adapt the layer
adapt_data = tf.constant(
    [
        "The Brain is wider than the Sky",
        "For put them side by side",
        "The one the other will contain",
        "With ease and You beside",
    ]
)

# Create a TextVectorization layer
text_vectorizer = layers.TextVectorization(output_mode="int")
# Index the vocabulary via `adapt()`
text_vectorizer.adapt(adapt_data)

# Try out the layer
print(
    "Encoded text:\n", text_vectorizer(["The Brain is deeper than the sea"]).numpy(),
)

# Create a simple model
inputs = keras.Input(shape=(None,), dtype="int64")
x = layers.Embedding(input_dim=text_vectorizer.vocabulary_size(), output_dim=16)(inputs)
x = layers.GRU(8)(x)
outputs = layers.Dense(1)(x)
model = keras.Model(inputs, outputs)

# Create a labeled dataset (which includes unknown tokens)
train_dataset = tf.data.Dataset.from_tensor_slices(
    (["The Brain is deeper than the sea", "for if they are held Blue to Blue"], [1, 0])
)

# Preprocess the string inputs, turning them into int sequences
train_dataset = train_dataset.batch(2).map(lambda x, y: (text_vectorizer(x), y))
# Train the model on the int sequences
print("\nTraining model...")
model.compile(optimizer="rmsprop", loss="mse")
model.fit(train_dataset)

# For inference, you can export a model that accepts strings as input
inputs = keras.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
outputs = model(x)
end_to_end_model = keras.Model(inputs, outputs)

# Call the end-to-end model on test data (which includes unknown tokens)
print("\nCalling end-to-end model on test string...")
test_data = tf.constant(["The one the other will absorb"])
test_output = end_to_end_model(test_data)
print("Model output:", test_output)

Encoded text:
 [[ 2 19 14  1  9  2  1]]



Training model...


1/1 [==============================] - ETA: 0s - loss: 0.4776

1/1 [==============================] - 3s 3s/step - loss: 0.4776



Calling end-to-end model on test string...


Model output: tf.Tensor([[0.04233753]], shape=(1, 1), dtype=float32)


You can see the `TextVectorization` layer in action, combined with an `Embedding` mode,
in the example
[text classification from scratch](https://keras.io/examples/nlp/text_classification_from_scratch/).

Note that when training such a model, for best performance, you should always
use the `TextVectorization` layer as part of the input pipeline.

### Encoding text as a dense matrix of ngrams with multi-hot encoding

This is how you should preprocess text to be passed to a `Dense` layer.

In [11]:
# Define some text data to adapt the layer
adapt_data = tf.constant(
    [
        "The Brain is wider than the Sky",
        "For put them side by side",
        "The one the other will contain",
        "With ease and You beside",
    ]
)
# Instantiate TextVectorization with "multi_hot" output_mode
# and ngrams=2 (index all bigrams)
text_vectorizer = layers.TextVectorization(output_mode="multi_hot", ngrams=2)
# Index the bigrams via `adapt()`
text_vectorizer.adapt(adapt_data)

# Try out the layer
print(
    "Encoded text:\n", text_vectorizer(["The Brain is deeper than the sea"]).numpy(),
)

# Create a simple model
inputs = keras.Input(shape=(text_vectorizer.vocabulary_size(),))
outputs = layers.Dense(1)(inputs)
model = keras.Model(inputs, outputs)

# Create a labeled dataset (which includes unknown tokens)
train_dataset = tf.data.Dataset.from_tensor_slices(
    (["The Brain is deeper than the sea", "for if they are held Blue to Blue"], [1, 0])
)

# Preprocess the string inputs, turning them into int sequences
train_dataset = train_dataset.batch(2).map(lambda x, y: (text_vectorizer(x), y))
# Train the model on the int sequences
print("\nTraining model...")
model.compile(optimizer="rmsprop", loss="mse")
model.fit(train_dataset)

# For inference, you can export a model that accepts strings as input
inputs = keras.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
outputs = model(x)
end_to_end_model = keras.Model(inputs, outputs)

# Call the end-to-end model on test data (which includes unknown tokens)
print("\nCalling end-to-end model on test string...")
test_data = tf.constant(["The one the other will absorb"])
test_output = end_to_end_model(test_data)
print("Model output:", test_output)

Encoded text:
 [[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]]

Training model...


1/1 [==============================] - ETA: 0s - loss: 1.0046

1/1 [==============================] - 0s 231ms/step - loss: 1.0046



Calling end-to-end model on test string...
Model output: tf.Tensor([[-0.54753447]], shape=(1, 1), dtype=float32)


### Encoding text as a dense matrix of ngrams with TF-IDF weighting

This is an alternative way of preprocessing text before passing it to a `Dense` layer.

In [12]:
# Define some text data to adapt the layer
adapt_data = tf.constant(
    [
        "The Brain is wider than the Sky",
        "For put them side by side",
        "The one the other will contain",
        "With ease and You beside",
    ]
)
# Instantiate TextVectorization with "tf-idf" output_mode
# (multi-hot with TF-IDF weighting) and ngrams=2 (index all bigrams)
text_vectorizer = layers.TextVectorization(output_mode="tf-idf", ngrams=2)
# Index the bigrams and learn the TF-IDF weights via `adapt()`

with tf.device("CPU"):
    # A bug that prevents this from running on GPU for now.
    text_vectorizer.adapt(adapt_data)

# Try out the layer
print(
    "Encoded text:\n", text_vectorizer(["The Brain is deeper than the sea"]).numpy(),
)

# Create a simple model
inputs = keras.Input(shape=(text_vectorizer.vocabulary_size(),))
outputs = layers.Dense(1)(inputs)
model = keras.Model(inputs, outputs)

# Create a labeled dataset (which includes unknown tokens)
train_dataset = tf.data.Dataset.from_tensor_slices(
    (["The Brain is deeper than the sea", "for if they are held Blue to Blue"], [1, 0])
)

# Preprocess the string inputs, turning them into int sequences
train_dataset = train_dataset.batch(2).map(lambda x, y: (text_vectorizer(x), y))
# Train the model on the int sequences
print("\nTraining model...")
model.compile(optimizer="rmsprop", loss="mse")
model.fit(train_dataset)

# For inference, you can export a model that accepts strings as input
inputs = keras.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
outputs = model(x)
end_to_end_model = keras.Model(inputs, outputs)

# Call the end-to-end model on test data (which includes unknown tokens)
print("\nCalling end-to-end model on test string...")
test_data = tf.constant(["The one the other will absorb"])
test_output = end_to_end_model(test_data)
print("Model output:", test_output)


Encoded text:
 [[5.461647  1.6945957 0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        1.0986123 1.0986123 1.0986123 0.        0.
  0.        0.        0.        0.        0.        0.        0.
  1.0986123 0.        0.        0.        0.        0.        0.
  0.        1.0986123 1.0986123 0.        0.        0.       ]]



Training model...


1/1 [==============================] - ETA: 0s - loss: 4.4868

1/1 [==============================] - 0s 239ms/step - loss: 4.4868



Calling end-to-end model on test string...
Model output: tf.Tensor([[0.25670475]], shape=(1, 1), dtype=float32)


## Important gotchas

### Working with lookup layers with very large vocabularies

You may find yourself working with a very large vocabulary in a `TextVectorization`, a `StringLookup` layer,
or an `IntegerLookup` layer. Typically, a vocabulary larger than 500MB would be considered "very large".

In such case, for best performance, you should avoid using `adapt()`.
Instead, pre-compute your vocabulary in advance
(you could use Apache Beam or TF Transform for this)
and store it in a file. Then load the vocabulary into the layer at construction
time by passing the filepath as the `vocabulary` argument.


### Using lookup layers on a TPU pod or with `ParameterServerStrategy`.

There is an outstanding issue that causes performance to degrade when using
a `TextVectorization`, `StringLookup`, or `IntegerLookup` layer while
training on a TPU pod or on multiple machines via `ParameterServerStrategy`.
This is slated to be fixed in TensorFlow 2.7.